apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-database
  namespace: homarr
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi