apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: ns-mealie
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi